language: node_js
node_js:
   - 0.6


services:
  - couchdb

script: "curl -X PUT localhost:5984/myapp_test"

after_script:
  - uname -a
  - ls -al
  - sudo ps -Al
  - whereis couchdb
  - ls -al /usr/lib/couchdb
  - sudo ls -al /proc/`pidof beam.smp`/cmdline
