language: node_js
node_js:
   - 0.6


services:
  - couchdb

script: "curl -X PUT localhost:5984/myapp_test"

after_script:
  - uname -a
  - sudo ls -al /var/lib/couchdb/
  - sudo ls -al /var/lib/couchdb/1.2.0
  - whereis couchdb
  - sudo ls -al /proc/`pidof beam.smp`/cmdline
